Rails.application.routes.draw do
# the priority is based upon order of creation: first created -> highest priority.
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# Root route
  root 'sessions#home'
# Custom routes here above the default resourceful routes
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
# OAuth2 OmniAuth callbacks routes
# Using math to avoid conflicts with other routes that may be using the same callback URL
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  # Include a class level ActiveRecord scope method (model object & class method name and URL to see the working feature e.g. Tag.bookmark_counts URL: /tags/bookmark_counts)

  # Include Nested resources ( show or Index ) and ( new ): Make sure These routes forms can display validations errors.  
  
  resources :bookmarks do
    resource :tags, only: [:index, :show, :new]
  end

  resources :tags
  resources :users, only: [:show]
  # This Are the Default Resourceful Routes Generated by the resource generator
  #resources :bookmarks  
  #resources :users  
  #resource :tags
end
