Rails.application.routes.draw do
# the priority is based upon order of creation: first created -> highest priority.
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# Root route
  root 'sessions#home'
# Custom routes here above the default resourceful routes
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
# OAuth2 OmniAuth callbacks routes
# Using math to avoid conflicts with other routes that may be using the same callback URL
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  # This Are the Default Resourceful Routes Generated by the resource generator
  resources :users
  resources :folders
  resources :bookmarks
  resources :tags

end
